import type { Phrase } from './types';

export const examplePhrases: Phrase[] = [
  {
    id: 4,
    text: 'I was really successful last year',
    label: 'successful last year',
    quadrant: 'past-strengths',
    x: -0.5,
    y: 0.6,
    recency: 0.2,
    importance: 0.6,
    sentenceNumber: 3,
    isRepeated: false,
    extractScore: 0.94,
    confidence: 0.87,
  },
  {
    id: 1,
    text: 'I have a strong support network',
    label: 'strong support network',
    quadrant: 'past-strengths',
    x: -0.6,
    y: 0.5,
    recency: 0.3,
    importance: 0.7,
    sentenceNumber: 5,
    isRepeated: true,
    extractScore: 0.98,
    confidence: 0.92,
  },
  {
    id: 2,
    text: 'I have this fear of failing again',
    label: 'fear of failing',
    quadrant: 'past-struggles',
    x: -0.7,
    y: -0.6,
    recency: 0.5,
    importance: 0.8,
    sentenceNumber: 8,
    isRepeated: false,
    extractScore: 0.96,
    confidence: 0.89,
  },
  {
    id: 8,
    text: 'The future feels really uncertain to me',
    label: 'uncertain future',
    quadrant: 'feared-future',
    x: 0.6,
    y: -0.6,
    recency: 0.6,
    importance: 0.8,
    sentenceNumber: 9,
    isRepeated: false,
    extractScore: 0.91,
    confidence: 0.85,
  },
  {
    id: 5,
    text: 'I\'m feeling overwhelmed right now',
    label: 'feeling overwhelmed',
    quadrant: 'past-struggles',
    x: -0.4,
    y: -0.5,
    recency: 0.7,
    importance: 0.75,
    sentenceNumber: 10,
    isRepeated: false,
    extractScore: 0.99,
    confidence: 0.95,
  },
  {
    id: 7,
    text: 'My confidence is growing every day',
    label: 'confidence growing',
    quadrant: 'preferred-future',
    x: 0.4,
    y: 0.6,
    recency: 0.8,
    importance: 0.7,
    sentenceNumber: 11,
    isRepeated: false,
    extractScore: 0.93,
    confidence: 0.78,
  },
  {
    id: 3,
    text: 'I really want more freedom in life',
    label: 'want more freedom',
    quadrant: 'preferred-future',
    x: 0.6,
    y: 0.7,
    recency: 0.9,
    importance: 0.9,
    sentenceNumber: 12,
    isRepeated: false,
    extractScore: 0.97,
    confidence: 0.91,
  },
  {
    id: 6,
    text: 'I can see a clear next step',
    label: 'clear next step',
    quadrant: 'preferred-future',
    x: 0.5,
    y: 0.5,
    recency: 0.95,
    importance: 0.85,
    sentenceNumber: 14,
    isRepeated: false,
    extractScore: 0.88,
    confidence: 0.82,
  },
];